//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEleitores2Entities : DbContext
    {
        public WebEleitores2Entities()
            : base("name=WebEleitores2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bairro> Bairro { get; set; }
        public DbSet<Cidade> Cidade { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Demanda> Demanda { get; set; }
        public DbSet<Domicilio> Domicilio { get; set; }
        public DbSet<Endereco> Endereco { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<EstadoCivil> EstadoCivil { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Localizacao> Localizacao { get; set; }
        public DbSet<LocalizacaoHistorico> LocalizacaoHistorico { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MotivoNaoRealizacaoVisita> MotivoNaoRealizacaoVisita { get; set; }
        public DbSet<OrigemDemanda> OrigemDemanda { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<PrazoDemanda> PrazoDemanda { get; set; }
        public DbSet<PrioridadeDemanda> PrioridadeDemanda { get; set; }
        public DbSet<StatusDemanda> StatusDemanda { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoDemanda> TipoDemanda { get; set; }
        public DbSet<TipoVisita> TipoVisita { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioResponsavel_TipoDemanda> UsuarioResponsavel_TipoDemanda { get; set; }
        public DbSet<Visita> Visita { get; set; }
    }
}
