USE DB_ARQUIVOS_DATASUS

/*UF*/
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('AC','Acre')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('AL','Alagoas')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('AM','Amazonas')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('AP','Amapá')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('BA','Bahia')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('CE','Ceará')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('DF','Distrito Federal')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('ES','Espirito Santo')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('GO','Goiás')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('MA','Maranhão')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('MG','Minas Gerais')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('MS','Mato Grosso do Sul')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('MT','Mato Grosso')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('PA','Pará')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('PB','Paraíba')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('PE','Pernambuco')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('PI','Piauí')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('PR','Paraná')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('RJ','Rio de Janeiro')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('RN','Rio Grande do Norte')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('RO','Rondônia')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('RR','Roraima')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('RS','Rio Grande do Sul')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('SC','Santa Catarina')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('SE','Sergipe')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('SP','São Paulo')
INSERT INTO [dbo].[EstadoUF]([Sigla] , [Nome] ) VALUES ('TO','Tocantins')

/*Tipo Arquivo*/
INSERT INTO [dbo].[TipoArquivo] ([Nome]) VALUES ('ER')
INSERT INTO [dbo].[TipoArquivo] ([Nome]) VALUES ('RD')
INSERT INTO [dbo].[TipoArquivo] ([Nome]) VALUES ('RJ')
INSERT INTO [dbo].[TipoArquivo] ([Nome]) VALUES ('SP')
